title: Game Feel & Juice
description: The ultimate "Wow Factor" toolkit for Unity developers. Professional trauma-based shake, time management, and visual juice system.
remote_theme: just-the-docs/just-the-docs

url: https://decnet-games.github.io
baseurl: /Game-Feel-Juice-Doc

aux_links:
  Unity Asset Store: https://assetstore.unity.com/
  Support: https://github.com/DecNet-Games/Game-Feel-Juice-Doc/issues
